addSbtPlugin("ch.epfl.scala"                % "sbt-scalafix"              % "0.10.4")
addSbtPlugin("com.github.cb372"             % "sbt-explicit-dependencies" % "0.3.1")
addSbtPlugin("com.timushev.sbt"             % "sbt-rewarn"                % "0.1.3")
addSbtPlugin("com.timushev.sbt"             % "sbt-updates"               % "0.6.4")
addSbtPlugin("org.scalameta"                % "sbt-scalafmt"              % "2.5.0")
